import { motion } from "framer-motion";
import { Play, Pause, Volume2, VolumeX, X, Sparkles } from "lucide-react";
import { useState } from "react";

export default function AIVideoPlayer() {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [progress, setProgress] = useState(45);
  const [isExpanded, setIsExpanded] = useState(true);

  const mockVideos = [
    {
      id: 1,
      title: "5K Running Form Guide",
      duration: "12:34",
      thumbnail: "via-blue-500",
      ai: "Generated by AI Coach",
      views: "2.4K"
    },
    {
      id: 2,
      title: "Advanced Trail Running Tips",
      duration: "8:45",
      thumbnail: "via-purple-500",
      ai: "AI Personalized Training",
      views: "1.8K"
    },
    {
      id: 3,
      title: "Recovery & Stretching Routine",
      duration: "15:20",
      thumbnail: "via-cyan-500",
      ai: "AI Recovery Assistant",
      views: "3.1K"
    }
  ];

  if (!isExpanded) {
    return (
      <motion.button
        onClick={() => setIsExpanded(true)}
        className="fixed bottom-4 left-4 md:left-80 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 p-4 shadow-lg hover:shadow-xl transition"
        whileHover={{ scale: 1.1 }}
        whileTap={{ scale: 0.95 }}
      >
        <Sparkles size={20} className="text-white" />
      </motion.button>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="fixed bottom-4 left-4 md:left-80 w-80 rounded-2xl border border-purple-500/30 bg-gradient-to-br from-zinc-950 via-purple-950 to-zinc-950 shadow-2xl shadow-purple-500/30 overflow-hidden"
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-purple-500/20">
        <div className="flex items-center gap-2">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity }}
            className="text-pink-500"
          >
            <Sparkles size={16} />
          </motion.div>
          <span className="text-sm font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
            AI Video Feed
          </span>
        </div>
        <button
          onClick={() => setIsExpanded(false)}
          className="hover:bg-zinc-800 p-1 rounded-lg transition"
        >
          <X size={16} className="text-zinc-400" />
        </button>
      </div>

      {/* Current Video */}
      <div className="p-4 space-y-3">
        <motion.div
          className="relative rounded-xl overflow-hidden bg-gradient-to-br from-purple-600 via-blue-500 to-cyan-500 h-48"
          whileHover={{ scale: 1.02 }}
        >
          <div className="absolute inset-0 flex items-center justify-center backdrop-blur-sm bg-black/30">
            <motion.div
              whileHover={{ scale: 1.2 }}
              whileTap={{ scale: 0.9 }}
              onClick={() => setIsPlaying(!isPlaying)}
              className="flex items-center justify-center w-16 h-16 rounded-full bg-white/30 backdrop-blur cursor-pointer hover:bg-white/40 transition"
            >
              {isPlaying ? (
                <Pause size={24} className="text-white ml-1" />
              ) : (
                <Play size={24} className="text-white ml-1" />
              )}
            </motion.div>
          </div>

          {/* Progress bar */}
          <div className="absolute bottom-0 w-full h-1 bg-black/50">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              className="h-full bg-gradient-to-r from-cyan-400 to-purple-500"
            />
          </div>
        </motion.div>

        <div>
          <motion.h3
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="font-bold text-sm text-white"
          >
            Advanced 10K Training: Peak Performance Strategies
          </motion.h3>
          <p className="text-xs text-purple-300 mt-1">🤖 AI Coach • 12:34 • 4.5K watching</p>
        </div>

        {/* Controls */}
        <div className="flex items-center justify-between">
          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={() => setIsPlaying(!isPlaying)}
            className="flex items-center gap-1 px-3 py-2 rounded-lg bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30 transition text-sm font-semibold"
          >
            {isPlaying ? <Pause size={14} /> : <Play size={14} />}
            {isPlaying ? "Pause" : "Play"}
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
            onClick={() => setIsMuted(!isMuted)}
            className="p-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 transition"
          >
            {isMuted ? (
              <VolumeX size={14} className="text-zinc-400" />
            ) : (
              <Volume2 size={14} className="text-zinc-400" />
            )}
          </motion.button>
        </div>
      </div>

      {/* Video Carousel */}
      <div className="border-t border-purple-500/20 p-3 space-y-2 max-h-64 overflow-y-auto">
        <p className="text-xs text-zinc-500 font-semibold px-1">Recommended AI Videos</p>
        {mockVideos.map((video, index) => (
          <motion.div
            key={video.id}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.1 }}
            className="flex gap-2 p-2 rounded-lg cursor-pointer hover:bg-purple-500/10 transition group"
          >
            <div
              className={`w-12 h-12 rounded-lg bg-gradient-to-br from-purple-500 ${video.thumbnail} flex-shrink-0`}
            />
            <div className="flex-1 min-w-0">
              <p className="text-xs font-semibold text-white truncate group-hover:text-cyan-400 transition">
                {video.title}
              </p>
              <p className="text-[10px] text-zinc-500">{video.duration}</p>
              <p className="text-[10px] text-purple-400">{video.ai}</p>
            </div>
            <motion.div
              whileHover={{ scale: 1.2 }}
              className="flex items-center justify-center w-6 h-6 rounded-full bg-cyan-500/20 flex-shrink-0 group-hover:bg-cyan-500/40 transition"
            >
              <Play size={10} className="text-cyan-400 ml-0.5" />
            </motion.div>
          </motion.div>
        ))}
      </div>
    </motion.div>
  );
}
